---
node_port: 8080
friend_nodes:
- node_name: 2
  node_port: 8081
new_files:
- "file6"
node_number: 1
owned_files_dir: "Node1/ownedFiles/"
new_files_dir: "Node1/newFiles/"
owned_files:
- "file1"
- "file2"
- "file3"
