---
new_files:
- "file6"
friend_nodes:
- node_name: 1
  node_port: 8080
- node_name: 2
  node_port: 8081
node_number: 4
node_port: 8083
owned_files:
- "file7"
- "file8"
new_files_dir: "Node4/newFiles/"
owned_files_dir: "Node4/ownedFiles/"
