---
new_files:
- "file1"
node_port: 8082
node_number: 3
friend_nodes:
- node_name: 4
  node_port: 8083
- node_name: 2
  node_port: 8081
new_files_dir: "Node3/newFiles/"
owned_files_dir: "Node3/ownedFiles/"
owned_files:
- "file6"
